---

- name:  Push nxos config
  hosts: hosts
  connection: local
  gather_facts: no

  vars:
    creds:
      username: admin
      password: password
  tasks:
    - nxos_config:
        provider: "{{ creds }}"
        commands: 
                - interface vlan {{ hostvars[inventory_hostname].mgmt_vlan}}
                - ip address 10.0.{{ hostvars[inventory_hostname].mgmt_vlan}}.{{ hostvars[inventory_hostname].last_octet}
                - hsrp {{ hostvars[inventory_hostname].mgmt_vlan}}
                - preempt
                - priority {{ hostvars[inventory_hostname].priority}}
                - ip 10.0.{{ hostvars[inventory_hostname].mgmt_vlan}}.1
        save_when: always


