---

- name:  Push IOS Config
  hosts: hosts
  connection: local
  gather_facts: no

  vars:
    creds:
      username: admin
      password: password
  tasks:
    - ios_config:
        provider: "{{ creds }}"
        commands: 
                -  int g1/0/1
                -  description Ansible
        save_when: always
